// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIJwCvIX4pW0nH9MZoW7K-4KdEW4FBdig',
    appId: '1:271811734394:web:930dfc675938c9bb9fc4c3',
    messagingSenderId: '271811734394',
    projectId: 'cmsc23-exer8-19d7e',
    authDomain: 'cmsc23-exer8-19d7e.firebaseapp.com',
    storageBucket: 'cmsc23-exer8-19d7e.appspot.com',
    measurementId: 'G-ZW1FKZCRB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ6Nu3q5sjQA_jffPb4Ab9c58fr-LGpng',
    appId: '1:271811734394:android:267df662b9eafab89fc4c3',
    messagingSenderId: '271811734394',
    projectId: 'cmsc23-exer8-19d7e',
    storageBucket: 'cmsc23-exer8-19d7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD06E1WGlwgZpl_PDsAsuAZvD-yTttgLJI',
    appId: '1:271811734394:ios:2d199eb16c48c4879fc4c3',
    messagingSenderId: '271811734394',
    projectId: 'cmsc23-exer8-19d7e',
    storageBucket: 'cmsc23-exer8-19d7e.appspot.com',
    iosBundleId: 'com.example.exer5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD06E1WGlwgZpl_PDsAsuAZvD-yTttgLJI',
    appId: '1:271811734394:ios:2d199eb16c48c4879fc4c3',
    messagingSenderId: '271811734394',
    projectId: 'cmsc23-exer8-19d7e',
    storageBucket: 'cmsc23-exer8-19d7e.appspot.com',
    iosBundleId: 'com.example.exer5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIJwCvIX4pW0nH9MZoW7K-4KdEW4FBdig',
    appId: '1:271811734394:web:95362971f9b78d639fc4c3',
    messagingSenderId: '271811734394',
    projectId: 'cmsc23-exer8-19d7e',
    authDomain: 'cmsc23-exer8-19d7e.firebaseapp.com',
    storageBucket: 'cmsc23-exer8-19d7e.appspot.com',
    measurementId: 'G-NY2365WC40',
  );
}
